package resources;

public class Constants {

    public static String trial = "-1\n1\n-2\n1";

    public static String frequencyConstants = "-15\n" +
            "-17\n" +
            "-16\n" +
            "-12\n" +
            "-4\n" +
            "+10\n" +
            "+10\n" +
            "-19\n" +
            "-18\n" +
            "-6\n" +
            "+4\n" +
            "+4\n" +
            "+5\n" +
            "-11\n" +
            "-4\n" +
            "-12\n" +
            "+1\n" +
            "-8\n" +
            "-10\n" +
            "-16\n" +
            "-18\n" +
            "+17\n" +
            "-16\n" +
            "-7\n" +
            "-5\n" +
            "+2\n" +
            "-4\n" +
            "-1\n" +
            "+13\n" +
            "-19\n" +
            "+12\n" +
            "+19\n" +
            "+5\n" +
            "+11\n" +
            "+1\n" +
            "-16\n" +
            "-8\n" +
            "+19\n" +
            "+15\n" +
            "-14\n" +
            "+1\n" +
            "-12\n" +
            "-17\n" +
            "+10\n" +
            "-3\n" +
            "+5\n" +
            "+7\n" +
            "+4\n" +
            "-10\n" +
            "+5\n" +
            "-7\n" +
            "+15\n" +
            "+11\n" +
            "+10\n" +
            "+19\n" +
            "-17\n" +
            "-3\n" +
            "+14\n" +
            "+8\n" +
            "-14\n" +
            "+7\n" +
            "+11\n" +
            "+16\n" +
            "-7\n" +
            "-1\n" +
            "+6\n" +
            "+4\n" +
            "-1\n" +
            "+15\n" +
            "+17\n" +
            "-10\n" +
            "+4\n" +
            "+16\n" +
            "-18\n" +
            "-10\n" +
            "-2\n" +
            "-18\n" +
            "-13\n" +
            "+15\n" +
            "-7\n" +
            "-14\n" +
            "-12\n" +
            "-2\n" +
            "+1\n" +
            "+7\n" +
            "+5\n" +
            "-1\n" +
            "-19\n" +
            "+1\n" +
            "+9\n" +
            "-20\n" +
            "-9\n" +
            "+1\n" +
            "+16\n" +
            "-7\n" +
            "+11\n" +
            "+14\n" +
            "-24\n" +
            "+4\n" +
            "-3\n" +
            "+21\n" +
            "-17\n" +
            "-10\n" +
            "-44\n" +
            "+13\n" +
            "+2\n" +
            "-9\n" +
            "-15\n" +
            "-17\n" +
            "-8\n" +
            "+13\n" +
            "+4\n" +
            "-1\n" +
            "+4\n" +
            "+1\n" +
            "+2\n" +
            "+6\n" +
            "-18\n" +
            "+1\n" +
            "+19\n" +
            "+4\n" +
            "+7\n" +
            "-15\n" +
            "-12\n" +
            "+4\n" +
            "+17\n" +
            "-3\n" +
            "-15\n" +
            "-19\n" +
            "-19\n" +
            "-17\n" +
            "+16\n" +
            "+17\n" +
            "-19\n" +
            "-3\n" +
            "-9\n" +
            "+4\n" +
            "+12\n" +
            "+12\n" +
            "+12\n" +
            "-21\n" +
            "+17\n" +
            "-19\n" +
            "-4\n" +
            "+16\n" +
            "-4\n" +
            "-18\n" +
            "-16\n" +
            "+15\n" +
            "+14\n" +
            "+12\n" +
            "-6\n" +
            "+16\n" +
            "-1\n" +
            "+16\n" +
            "+6\n" +
            "-4\n" +
            "+6\n" +
            "-4\n" +
            "+11\n" +
            "+20\n" +
            "-7\n" +
            "+12\n" +
            "+51\n" +
            "+19\n" +
            "+15\n" +
            "-2\n" +
            "+12\n" +
            "-9\n" +
            "-6\n" +
            "+1\n" +
            "+10\n" +
            "+1\n" +
            "+19\n" +
            "+8\n" +
            "+3\n" +
            "-1\n" +
            "-19\n" +
            "-2\n" +
            "+4\n" +
            "+11\n" +
            "+8\n" +
            "+2\n" +
            "+10\n" +
            "+14\n" +
            "+4\n" +
            "-8\n" +
            "+9\n" +
            "-13\n" +
            "+18\n" +
            "+5\n" +
            "-8\n" +
            "+15\n" +
            "-19\n" +
            "-13\n" +
            "-13\n" +
            "+10\n" +
            "-4\n" +
            "-16\n" +
            "+17\n" +
            "-3\n" +
            "+7\n" +
            "+20\n" +
            "+18\n" +
            "-12\n" +
            "+13\n" +
            "-10\n" +
            "+14\n" +
            "+19\n" +
            "+17\n" +
            "+7\n" +
            "+7\n" +
            "+3\n" +
            "+17\n" +
            "-8\n" +
            "-4\n" +
            "+1\n" +
            "-8\n" +
            "-12\n" +
            "-1\n" +
            "-15\n" +
            "+9\n" +
            "-7\n" +
            "+6\n" +
            "+10\n" +
            "+4\n" +
            "+4\n" +
            "-14\n" +
            "-9\n" +
            "-19\n" +
            "+13\n" +
            "-5\n" +
            "+19\n" +
            "-17\n" +
            "-1\n" +
            "+5\n" +
            "-13\n" +
            "+2\n" +
            "+4\n" +
            "+15\n" +
            "+8\n" +
            "+10\n" +
            "+8\n" +
            "+17\n" +
            "+17\n" +
            "+1\n" +
            "+6\n" +
            "-15\n" +
            "+5\n" +
            "+12\n" +
            "+11\n" +
            "-3\n" +
            "+12\n" +
            "-6\n" +
            "-17\n" +
            "-17\n" +
            "+10\n" +
            "-15\n" +
            "-5\n" +
            "-1\n" +
            "-4\n" +
            "-3\n" +
            "+5\n" +
            "-21\n" +
            "-2\n" +
            "-18\n" +
            "+3\n" +
            "+19\n" +
            "+10\n" +
            "+15\n" +
            "-5\n" +
            "+17\n" +
            "-14\n" +
            "+6\n" +
            "+7\n" +
            "+3\n" +
            "-11\n" +
            "+6\n" +
            "+20\n" +
            "-9\n" +
            "+6\n" +
            "+6\n" +
            "-10\n" +
            "-9\n" +
            "-8\n" +
            "+16\n" +
            "+19\n" +
            "-9\n" +
            "+5\n" +
            "+6\n" +
            "-3\n" +
            "+12\n" +
            "-8\n" +
            "+7\n" +
            "-1\n" +
            "+16\n" +
            "+17\n" +
            "-19\n" +
            "+3\n" +
            "+11\n" +
            "+18\n" +
            "+19\n" +
            "-16\n" +
            "+11\n" +
            "+11\n" +
            "+5\n" +
            "+11\n" +
            "-25\n" +
            "+13\n" +
            "-7\n" +
            "+9\n" +
            "-18\n" +
            "-16\n" +
            "+18\n" +
            "+22\n" +
            "+35\n" +
            "+82\n" +
            "+8\n" +
            "+11\n" +
            "+19\n" +
            "+17\n" +
            "-11\n" +
            "+19\n" +
            "-16\n" +
            "+1\n" +
            "+21\n" +
            "+17\n" +
            "+18\n" +
            "-9\n" +
            "-10\n" +
            "+8\n" +
            "-15\n" +
            "+4\n" +
            "+20\n" +
            "-19\n" +
            "-10\n" +
            "+2\n" +
            "+22\n" +
            "+11\n" +
            "-5\n" +
            "+16\n" +
            "-7\n" +
            "-7\n" +
            "-15\n" +
            "-11\n" +
            "+28\n" +
            "+13\n" +
            "-7\n" +
            "+1\n" +
            "+3\n" +
            "+11\n" +
            "-7\n" +
            "+3\n" +
            "-15\n" +
            "+34\n" +
            "+5\n" +
            "-22\n" +
            "+7\n" +
            "-15\n" +
            "-2\n" +
            "+29\n" +
            "-45\n" +
            "-51\n" +
            "-6\n" +
            "+10\n" +
            "+6\n" +
            "+22\n" +
            "-17\n" +
            "-24\n" +
            "-12\n" +
            "+38\n" +
            "-71\n" +
            "+46\n" +
            "-10\n" +
            "-19\n" +
            "-15\n" +
            "-115\n" +
            "-26\n" +
            "-17\n" +
            "-2\n" +
            "+4\n" +
            "-15\n" +
            "+9\n" +
            "-4\n" +
            "-10\n" +
            "-14\n" +
            "-4\n" +
            "-18\n" +
            "-18\n" +
            "+21\n" +
            "+8\n" +
            "+13\n" +
            "+15\n" +
            "-13\n" +
            "-6\n" +
            "-6\n" +
            "+7\n" +
            "+4\n" +
            "+12\n" +
            "-7\n" +
            "-20\n" +
            "-14\n" +
            "-22\n" +
            "-2\n" +
            "-16\n" +
            "-7\n" +
            "-2\n" +
            "+12\n" +
            "-24\n" +
            "-18\n" +
            "+35\n" +
            "-45\n" +
            "+128\n" +
            "-2\n" +
            "+22\n" +
            "-10\n" +
            "-17\n" +
            "+14\n" +
            "-4\n" +
            "-11\n" +
            "+13\n" +
            "-6\n" +
            "+29\n" +
            "-40\n" +
            "-11\n" +
            "+7\n" +
            "-25\n" +
            "+5\n" +
            "-10\n" +
            "+58\n" +
            "-171\n" +
            "-169\n" +
            "-93\n" +
            "-106\n" +
            "-61611\n" +
            "-19\n" +
            "-3\n" +
            "-3\n" +
            "+14\n" +
            "+1\n" +
            "-6\n" +
            "+11\n" +
            "-7\n" +
            "-16\n" +
            "-13\n" +
            "-7\n" +
            "-14\n" +
            "+12\n" +
            "+4\n" +
            "-8\n" +
            "-12\n" +
            "-2\n" +
            "-3\n" +
            "+14\n" +
            "-18\n" +
            "-10\n" +
            "+3\n" +
            "-7\n" +
            "-15\n" +
            "-3\n" +
            "-13\n" +
            "+3\n" +
            "+1\n" +
            "-15\n" +
            "-5\n" +
            "-11\n" +
            "+15\n" +
            "+14\n" +
            "-9\n" +
            "+6\n" +
            "+2\n" +
            "+13\n" +
            "+5\n" +
            "+15\n" +
            "-9\n" +
            "+5\n" +
            "+2\n" +
            "+15\n" +
            "+18\n" +
            "+16\n" +
            "-17\n" +
            "-5\n" +
            "-18\n" +
            "+1\n" +
            "+6\n" +
            "-25\n" +
            "-17\n" +
            "+5\n" +
            "+13\n" +
            "-14\n" +
            "+7\n" +
            "+9\n" +
            "-11\n" +
            "-19\n" +
            "-13\n" +
            "-15\n" +
            "+9\n" +
            "-10\n" +
            "+5\n" +
            "+7\n" +
            "+6\n" +
            "-16\n" +
            "-11\n" +
            "+1\n" +
            "+1\n" +
            "+15\n" +
            "-18\n" +
            "-9\n" +
            "-1\n" +
            "+6\n" +
            "-17\n" +
            "-5\n" +
            "-19\n" +
            "+15\n" +
            "+7\n" +
            "-15\n" +
            "+7\n" +
            "+19\n" +
            "-7\n" +
            "-10\n" +
            "-5\n" +
            "-1\n" +
            "+17\n" +
            "+15\n" +
            "-3\n" +
            "+14\n" +
            "+5\n" +
            "-7\n" +
            "-8\n" +
            "-14\n" +
            "-8\n" +
            "-23\n" +
            "-18\n" +
            "-14\n" +
            "+11\n" +
            "+1\n" +
            "+7\n" +
            "-18\n" +
            "+1\n" +
            "-5\n" +
            "+6\n" +
            "-9\n" +
            "-7\n" +
            "-19\n" +
            "-2\n" +
            "+17\n" +
            "-2\n" +
            "+8\n" +
            "-10\n" +
            "+7\n" +
            "-22\n" +
            "-14\n" +
            "-10\n" +
            "-8\n" +
            "+17\n" +
            "-19\n" +
            "-12\n" +
            "+15\n" +
            "+9\n" +
            "-16\n" +
            "+9\n" +
            "+16\n" +
            "-5\n" +
            "-18\n" +
            "-4\n" +
            "-7\n" +
            "-4\n" +
            "-17\n" +
            "+14\n" +
            "+1\n" +
            "+8\n" +
            "-10\n" +
            "+3\n" +
            "-19\n" +
            "+7\n" +
            "-11\n" +
            "+14\n" +
            "+12\n" +
            "+12\n" +
            "-4\n" +
            "-19\n" +
            "-10\n" +
            "-8\n" +
            "-1\n" +
            "-16\n" +
            "-2\n" +
            "-7\n" +
            "-15\n" +
            "-5\n" +
            "-2\n" +
            "-15\n" +
            "+11\n" +
            "-17\n" +
            "-1\n" +
            "-5\n" +
            "+1\n" +
            "-9\n" +
            "-3\n" +
            "-13\n" +
            "-14\n" +
            "+8\n" +
            "-17\n" +
            "-4\n" +
            "-4\n" +
            "-12\n" +
            "+3\n" +
            "+1\n" +
            "+19\n" +
            "+2\n" +
            "+2\n" +
            "+5\n" +
            "-2\n" +
            "-9\n" +
            "+19\n" +
            "+17\n" +
            "-2\n" +
            "-19\n" +
            "+13\n" +
            "+12\n" +
            "+16\n" +
            "+10\n" +
            "-11\n" +
            "+12\n" +
            "-5\n" +
            "+10\n" +
            "+5\n" +
            "-7\n" +
            "+18\n" +
            "+11\n" +
            "+1\n" +
            "-15\n" +
            "+6\n" +
            "-10\n" +
            "+17\n" +
            "-19\n" +
            "+18\n" +
            "+8\n" +
            "+11\n" +
            "-2\n" +
            "+19\n" +
            "-21\n" +
            "-18\n" +
            "-18\n" +
            "-15\n" +
            "+4\n" +
            "+18\n" +
            "+13\n" +
            "-4\n" +
            "+14\n" +
            "+19\n" +
            "-7\n" +
            "+9\n" +
            "+7\n" +
            "+21\n" +
            "+18\n" +
            "-4\n" +
            "+18\n" +
            "+15\n" +
            "-6\n" +
            "+16\n" +
            "+8\n" +
            "-12\n" +
            "+3\n" +
            "-18\n" +
            "+4\n" +
            "+20\n" +
            "-8\n" +
            "-9\n" +
            "+15\n" +
            "+12\n" +
            "+1\n" +
            "+17\n" +
            "+6\n" +
            "-9\n" +
            "+13\n" +
            "-12\n" +
            "-13\n" +
            "+10\n" +
            "-6\n" +
            "-1\n" +
            "+17\n" +
            "+12\n" +
            "-18\n" +
            "+4\n" +
            "+5\n" +
            "+11\n" +
            "-6\n" +
            "+1\n" +
            "+14\n" +
            "-17\n" +
            "+4\n" +
            "+17\n" +
            "+9\n" +
            "-15\n" +
            "-8\n" +
            "+7\n" +
            "+5\n" +
            "-7\n" +
            "+14\n" +
            "+5\n" +
            "+13\n" +
            "+7\n" +
            "-1\n" +
            "-7\n" +
            "-10\n" +
            "+14\n" +
            "-6\n" +
            "+26\n" +
            "+15\n" +
            "+1\n" +
            "+13\n" +
            "+13\n" +
            "-11\n" +
            "-6\n" +
            "+16\n" +
            "-2\n" +
            "-19\n" +
            "+8\n" +
            "-14\n" +
            "+7\n" +
            "-16\n" +
            "+21\n" +
            "+17\n" +
            "+3\n" +
            "+21\n" +
            "+4\n" +
            "-8\n" +
            "-2\n" +
            "+28\n" +
            "+1\n" +
            "-17\n" +
            "+14\n" +
            "-9\n" +
            "+2\n" +
            "-18\n" +
            "+12\n" +
            "+10\n" +
            "+18\n" +
            "-17\n" +
            "-15\n" +
            "-18\n" +
            "+2\n" +
            "+1\n" +
            "-31\n" +
            "+8\n" +
            "-20\n" +
            "-2\n" +
            "-20\n" +
            "-21\n" +
            "+9\n" +
            "+8\n" +
            "+10\n" +
            "-45\n" +
            "+20\n" +
            "+27\n" +
            "+10\n" +
            "-65\n" +
            "+12\n" +
            "-17\n" +
            "-9\n" +
            "-11\n" +
            "+24\n" +
            "+7\n" +
            "-46\n" +
            "-13\n" +
            "+12\n" +
            "-19\n" +
            "+1\n" +
            "-25\n" +
            "+13\n" +
            "-5\n" +
            "-19\n" +
            "+9\n" +
            "-14\n" +
            "-6\n" +
            "+14\n" +
            "+4\n" +
            "-22\n" +
            "-5\n" +
            "-2\n" +
            "-7\n" +
            "+34\n" +
            "+13\n" +
            "-17\n" +
            "-8\n" +
            "+19\n" +
            "+22\n" +
            "-13\n" +
            "+6\n" +
            "+6\n" +
            "+6\n" +
            "-16\n" +
            "+25\n" +
            "+12\n" +
            "+8\n" +
            "-16\n" +
            "-32\n" +
            "-12\n" +
            "-36\n" +
            "-21\n" +
            "+1\n" +
            "+13\n" +
            "-17\n" +
            "-11\n" +
            "+9\n" +
            "+13\n" +
            "+7\n" +
            "-11\n" +
            "-13\n" +
            "-10\n" +
            "-14\n" +
            "+18\n" +
            "+4\n" +
            "-25\n" +
            "+4\n" +
            "-12\n" +
            "+6\n" +
            "-20\n" +
            "-10\n" +
            "+17\n" +
            "-11\n" +
            "+3\n" +
            "-10\n" +
            "-4\n" +
            "-10\n" +
            "+9\n" +
            "-15\n" +
            "-6\n" +
            "+17\n" +
            "+13\n" +
            "-28\n" +
            "-8\n" +
            "+4\n" +
            "-20\n" +
            "+13\n" +
            "-6\n" +
            "+12\n" +
            "-17\n" +
            "-9\n" +
            "-14\n" +
            "+13\n" +
            "-4\n" +
            "+57\n" +
            "-5\n" +
            "+37\n" +
            "-14\n" +
            "+6\n" +
            "-15\n" +
            "-16\n" +
            "-2\n" +
            "-31\n" +
            "+3\n" +
            "+88\n" +
            "+8\n" +
            "-22\n" +
            "+6\n" +
            "+22\n" +
            "+17\n" +
            "+9\n" +
            "-31\n" +
            "-121\n" +
            "-45\n" +
            "+21\n" +
            "-82\n" +
            "-37\n" +
            "-93\n" +
            "-31\n" +
            "-17\n" +
            "+117\n" +
            "-61928\n" +
            "+11\n" +
            "-17\n" +
            "-10\n" +
            "+9\n" +
            "+10\n" +
            "-18\n" +
            "+10\n" +
            "-7\n" +
            "-6\n" +
            "-5\n" +
            "-4\n" +
            "+19\n" +
            "-12\n" +
            "+17\n" +
            "+9\n" +
            "-16\n" +
            "+1\n" +
            "+10\n" +
            "-12\n" +
            "-6\n" +
            "+19\n" +
            "-4\n" +
            "-11\n" +
            "-15\n" +
            "-7\n" +
            "+13\n" +
            "-10\n" +
            "+2\n" +
            "-15\n" +
            "+2\n" +
            "-8\n" +
            "+17\n" +
            "+9\n" +
            "+4\n" +
            "-8\n" +
            "-19\n" +
            "+7\n" +
            "-8\n" +
            "-12\n" +
            "-1\n" +
            "-5\n" +
            "+2\n" +
            "+6\n" +
            "-15\n" +
            "+8\n" +
            "+11\n" +
            "+13\n" +
            "-18\n" +
            "-8\n" +
            "-11\n" +
            "-16\n" +
            "+13\n" +
            "+6\n" +
            "-18\n" +
            "-10\n" +
            "+19\n" +
            "+2\n" +
            "-8\n" +
            "-10\n" +
            "-13\n" +
            "-19\n" +
            "+15\n" +
            "+8\n" +
            "-5\n" +
            "+19\n" +
            "+3\n" +
            "+12\n" +
            "-16\n" +
            "-5\n" +
            "-5\n" +
            "-18\n" +
            "-11\n" +
            "-7\n" +
            "+4\n" +
            "-5\n" +
            "+15\n" +
            "-1\n" +
            "+10\n" +
            "-6\n" +
            "-5\n" +
            "-16\n" +
            "+9\n" +
            "+10\n" +
            "+16\n" +
            "+14\n" +
            "-15\n" +
            "+10\n" +
            "-18\n" +
            "-11\n" +
            "-13\n" +
            "-11\n" +
            "-2\n" +
            "-9\n" +
            "-17\n" +
            "+11\n" +
            "+8\n" +
            "+125143";

    public static String boxNames = "mphcuiszrnjzxwkbgdzqeoyxfa\n" +
            "mihcuisgrnjzxwkbgdtqeoylia\n" +
            "mphauisvrnjgxwkbgdtqeiylfa\n" +
            "mphcuisnrnjzxwkbgdgqeoylua\n" +
            "mphcuisurnjzxwkbgdtqeoilfi\n" +
            "mkhcuisvrnjzowkbgdteeoylfa\n" +
            "mphcoicvrnjzxwksgdtqeoylfa\n" +
            "mxhcuisvrndzxwkbgdtqeeylfa\n" +
            "dphcuisijnjzxwkbgdtqeoylfa\n" +
            "mihvuisvrqjzxwkbgdtqeoylfa\n" +
            "mphcuisrrnvzxwkbgdtqeodlfa\n" +
            "mphtuisdrnjzxskbgdtqeoylfa\n" +
            "mphcutmvsnjzxwkbgdtqeoylfa\n" +
            "mphcunsvrnjzswkggdtqeoylfa\n" +
            "mphcuisvrwjzxwkbpdtqeoylfr\n" +
            "mphcujsdrnjzxwkbgdtqeovlfa\n" +
            "mpfcuisvrdjzxwkbgdtteoylfa\n" +
            "mppcuisvrpjzxwkbgdtqeoywfa\n" +
            "mphcuisvrnjzxwkbfptqroylfa\n" +
            "mphcuisvrnjzxwkbgstoeoysfa\n" +
            "mphcufsvrnjzcwkbgdeqeoylfa\n" +
            "mphcuissrnjzxwkbgdkquoylfa\n" +
            "sphcuxsvrnjzxwkbgdtqioylfa\n" +
            "mphcuiivrhjzxwkbgdtqevylfa\n" +
            "echcuisvrnjzxwkbgltqeoylfa\n" +
            "mphcuisvrljexwkbvdtqeoylfa\n" +
            "mpjcuisvrnjzxwkhidtqeoylfa\n" +
            "mphcuisvrfjzmwkbgdtqeoylfl\n" +
            "mwhcuisvrnjzxwkbgdtqeoytfm\n" +
            "mphcuisvrsjzxwkbgdaqeoylfh\n" +
            "mohcuisvrnjzxwkbgdtqtoymfa\n" +
            "maycuisvrnjzxwkbgdtqboylfa\n" +
            "pphcuisvqnjzxwkbgdtqeoylfd\n" +
            "mprcuisvrnjtxwmbgdtqeoylfa\n" +
            "mfhcuisgrnjzxckbgdtqeoylfa\n" +
            "mphiubsvrnjzxwkbgdtqeoyufa\n" +
            "dphctisvrnjzxwkbgdtqeoylfk\n" +
            "mphcuisvrnjznwksgdtqeoyzfa\n" +
            "mpwcuisvrnjziwkbgdtqaoylfa\n" +
            "mphduzsvrnjznwkbgdtqeoylfa\n" +
            "mphccisvrnjzxwebgdtqeoylqa\n" +
            "xphcuisvrnjzxwkfvdtqeoylfa\n" +
            "mphcupsvrnjzxwkbgdtfeoylpa\n" +
            "mphcuisvrtjzjwkbgdtqeoylfe\n" +
            "mpbcuisvrnjzxwkbgdmieoylfa\n" +
            "mphcuisvrnjzxwkbgjtqetylaa\n" +
            "mphcuisvrnjzxwpbgdtgdoylfa\n" +
            "ophcufsvrqjzxwkbgdtqeoylfa\n" +
            "iphcuhsvrnjzxwkbgetqeoylfa\n" +
            "mphcuisvunjzxwwbgdtqeoylqa\n" +
            "mphcpisvrnjzowkbgdtveoylfa\n" +
            "mphcuisvrnjzxhkbgdtqeotlla\n" +
            "mphcuisvrnjzxwkbodtgeoylha\n" +
            "mphcuisvrjjzxwkbwdtqtoylfa\n" +
            "mphcwisvrnjnxwkbgjtqeoylfa\n" +
            "mplcuicqrnjzxwkbgdtqeoylfa\n" +
            "mphcuisvrnjzxydbgdtqeoylfn\n" +
            "ophckisvrnjzxwkbgdtqeozlfa\n" +
            "mphcuisvrkjzxwkbgdtteoblfa\n" +
            "yphcuisvrnjcxwkbggtqeoylfa\n" +
            "mphcuisvrnazxwfbqdtqeoylfa\n" +
            "mphcuisvrmjzxwkbgdtlwoylfa\n" +
            "mphctksvrnjzxwibgdtqeoylfa\n" +
            "mphcuisprnjzxlebgdtqeoylfa\n" +
            "mphcuisnrnjzxakbgdtueoylfa\n" +
            "mphcuiavrnjoxwtbgdtqeoylfa\n" +
            "nphcuisvrnjzxwkbgdtqzoylfk\n" +
            "mphcuisrrnjmxwkbgdtqdoylfa\n" +
            "mphcuisvrujzxwkvgdtqehylfa\n" +
            "mphcuisvrnfzxwkogdtqebylfa\n" +
            "mphcuisvrnjwdwkbgdtqeoyxfa\n" +
            "mphcuisvrntzxwkrgxtqeoylfa\n" +
            "mpzcuisvrnjzxwebgdtqeoylsa\n" +
            "aphcuikvrnjzxwwbgdtqeoylfa\n" +
            "mphcqisvrnjzxwkpgdtqeoelfa\n" +
            "mphcuusvrnjzxwkbgdtjeodlfa\n" +
            "mphcuisvrnjzewkbgdtteoylza\n" +
            "mphcuisvanjzxwkbgdtheoylfc\n" +
            "mphcjishrnjzxwkbgltqeoylfa\n" +
            "mpxcuislrnjzxwkbgdtqeoynfa\n" +
            "mphcuisvrnjjxwkbgdtmeoxlfa\n" +
            "mphcimsvrnjzxwkbsdtqeoylfa\n" +
            "mphcxisvcnjzxwjbgdtqeoylfa\n" +
            "mphcuisbrvjzxwkbgdtqeoymfa\n" +
            "mplcuisvrnjzxwkbgdtaenylfa\n" +
            "mphcuihvrnjzxwkygytqeoylfa\n" +
            "mphcbisvrnjzxhkbgdtqezylfa\n" +
            "mphcuisarnjzxwkbgatqeoylfv\n" +
            "mphcumsvrnjzxwkbgdrqebylfa\n" +
            "mlhcuisvrnwzxwkbgdtqeoylfx\n" +
            "mpkcuisvrkjzxwkbgdtqeoylfo\n" +
            "mphcuissrnjzxwkbgdtqmoylfc\n" +
            "mphcuiwvrnjuxwkfgdtqeoylfa\n" +
            "mphcuicvlnjzxwkbgdvqeoylfa\n" +
            "mphcuisvrvvzxwkbfdtqeoylfa\n" +
            "myhcuisvrnjpxwkbgntqeoylfa\n" +
            "mpocuisvrnjzxwtbgitqeoylfa\n" +
            "mphcuisvrnjzxwkbgdtwewyqfa\n" +
            "mphcuisvtnjzxwwbgdtqeoolfa\n" +
            "mphcuisvrnjzxgkbgdyqeoyyfa\n" +
            "mphcuisvrdjzxwkbgpyqeoylfa\n" +
            "bphcuisvrnjzxwkbgxtqefylfa\n" +
            "sphcuisvrdjzxwktgdtqeoylfa\n" +
            "mphcuvsvrnjmxwobgdtqeoylfa\n" +
            "mphcuisvrnjzxwkbsdtqeuylfb\n" +
            "mnhcmisvynjzxwkbgdtqeoylfa\n" +
            "mphckisvrnjzxwkhgdkqeoylfa\n" +
            "mpacuisvrnjzxwkbgdtqeoolaa\n" +
            "mpgcuisvrnjzxwkbzdtqeoynfa\n" +
            "mphcuisvrojzxwkbzdtqeoylga\n" +
            "mphcuisvknjfxwkbydtqeoylfa\n" +
            "mphcuistrnjzxwkbgdqqeuylfa\n" +
            "bpvcuiszrnjzxwkbgdtqeoylfa\n" +
            "mphcuxsvrnjzswkbgdtqeoelfa\n" +
            "mphcuisvbnjzxwlbgdtqeoylla\n" +
            "mphcuisvonczxwkbgktqeoylfa\n" +
            "mphcuisvrnkzxwvbgdtquoylfa\n" +
            "mphcuisvrnjzxokfgdtqeoylia\n" +
            "tphcuisvrnjzxwkbjdwqeoylfa\n" +
            "mihcuisvrnjzpwibgdtqeoylfa\n" +
            "mphcuisvrejzxwkbgdtqjuylfa\n" +
            "mprcuisvrnjixwkxgdtqeoylfa\n" +
            "mpqcuiszrnjzxwkbgdtqeodlfa\n" +
            "mphcuasvrnjzzakbgdtqeoylva\n" +
            "mphcuisvrnjzmwkbtdtqeoycfa\n" +
            "mphcuisvrnjzxwkbcdtqioylxa\n" +
            "mphckisvrnjzxwkbcdtqeoylfm\n" +
            "mphcuisvrnjuxwbogdtqeoylfa\n" +
            "mphcuisdrnjzxwkbldtqeoylfx\n" +
            "mphcuisvrnjoxwkbgdtqeyyyfa\n" +
            "mphcuicvqnjzxwkbgdtqeoylna\n" +
            "mpmcuisvrnjzxwkbgdtqktylfa\n" +
            "mphcuisvrnqzxwkggdtqeoykfa\n" +
            "mphcuisvryjzxwkbydtqejylfa\n" +
            "mphcugsvrnjzxwkbghtqeeylfa\n" +
            "rphcuusvrnjzxwkwgdtqeoylfa\n" +
            "zphwuiyvrnjzxwkbgdtqeoylfa\n" +
            "cphcuivvrnjzxwkbgdtqenylfa\n" +
            "mphcuisvrnjzxwkagotqevylfa\n" +
            "mprcuisvrcjzxwkbgdtqeoytfa\n" +
            "mphjugsvrnezxwkbgdtqeoylfa\n" +
            "mphcuisvryjzxwkbgltqeoylaa\n" +
            "mphcursvrnjzxfkbgdtqeoydfa\n" +
            "mphcuisvrcuzxwkbgdtqeoylfw\n" +
            "mphcuisvrijzxwkbgdtqeoelfh\n" +
            "xphcuisvenjzxjkbgdtqeoylfa\n" +
            "mphcuisvrnazxwkbgdeqeoylaa\n" +
            "mphcuisbrsjzxwkbgdtqeoygfa\n" +
            "mlhvuisvrnjzxwkbgdtqeoylfh\n" +
            "mphcuisvrnjzxukbgdtqeoyhfy\n" +
            "mpzcuilvrnjzawkbgdtqeoylfa\n" +
            "hphcuisjfnjzxwkbgdtqeoylfa\n" +
            "mahcuisvrnjzxwkegdtqeoylfi\n" +
            "mphcuixvrnjzcwkbgdtqetylfa\n" +
            "mphcuisvrnjzxwkdgdtqeoklfj\n" +
            "mlhcuisvrnjzxwkbgdteeoylka\n" +
            "mphcuifvrnjbxwkrgdtqeoylfa\n" +
            "mphcuasvrnjzzwkbgdtqeoylva\n" +
            "mphcuisvrnjzxwkboutqeoylba\n" +
            "mbhcuisvcnjzxwklgdtqeoylfa\n" +
            "mpbcuisvrnjzxgkbgdtqesylfa\n" +
            "mphcuisvrnjfswkbgdtqeoylfd\n" +
            "mphcuisvrnjzxwkbgdoweoysfa\n" +
            "uphcuisvrnjzrwkbgdtqelylfa\n" +
            "mphcuisvrnjzxwkbgdtqyoylsi\n" +
            "mpqcuiqvxnjzxwkbgdtqeoylfa\n" +
            "mphcuisorfjzxwkbgatqeoylfa\n" +
            "mphcuisvrntfxwkbzdtqeoylfa\n" +
            "mphcuisvrnrzxwkbgdtueoylfl\n" +
            "mphcuisvrnjzewkagdtyeoylfa\n" +
            "mpocuisdrnjzxwkbgdtqeozlfa\n" +
            "mphcuisvrnjjxwkbgdtoeoylfm\n" +
            "mphcuisvenjzxwkbgdtqwoylza\n" +
            "mpmcuisvrnjzxwkbgdtqeoxlfr\n" +
            "mphcuisvgnjhxwkbgdtqeoplfa\n" +
            "mphcuisvrnjzowkdgdtqeoyyfa\n" +
            "mphcuisqynjzxwkbgdtqeoylda\n" +
            "hphcuisvgnjzxwkbgdtbeoylfa\n" +
            "iphcuipvrnuzxwkbgdtqeoylfa\n" +
            "mphcuisvrnjzsikbpdtqeoylfa\n" +
            "mpwcuhsvrnjzxbkbgdtqeoylfa\n" +
            "mnhjuisvcnjzxwkbgdtqeoylfa\n" +
            "mphcudsvrnjzxwkbgdtqloilfa\n" +
            "mpncuiwvrwjzxwkbgdtqeoylfa\n" +
            "mphcuisvrnjgawkbgdtqeoylya\n" +
            "mphcuisvrnjzxwkbggtteoslfa\n" +
            "mphcuisvrnjzxwkbgdvqeoylpe\n" +
            "mphcuisvrnczxfkbgktqeoylfa\n" +
            "mphcuifvrnjzxwkbgdbmeoylfa\n" +
            "mphcuisvrnjytwkbgdtqeoylla\n" +
            "mphcuisvrnjzxwkbgdtjeoxlfn\n" +
            "mphjuisvrnjzxwkbghtqeoyffa\n" +
            "mphcuisvrnjzxkrbgdtqeoylaa\n" +
            "mphcbisvrnjzxwkbgttqeoylfs\n" +
            "mphkuksvbnjzxwkbgdtqeoylfa\n" +
            "nphcuidvrnjzxwhbgdtqeoylfa\n" +
            "mphguzsvrnjzxwkbgdaqeoylfa\n" +
            "mihcuisfrnjzxwkbgdtqhoylfa\n" +
            "mphcuisvrnrzxwpbgdtqesylfa\n" +
            "zphcuisvrnjzxwkbddtqeoylaa\n" +
            "mphcuigvmnjzxwkbgdtqeoylba\n" +
            "mjhcuisvrnjzxjkbgdtqeoylha\n" +
            "mphnuisvrnjznwkbgdtqnoylfa\n" +
            "mkhcuisvrnjcxwkbgdqqeoylfa\n" +
            "mphcuisvenjzxwbbqdtqeoylfa\n" +
            "qphcuisnrnjzawkbgdtqeoylfa\n" +
            "mphcuisvrdjzxwkbgdtqeoywca\n" +
            "mphcuzsvvnjzxwfbgdtqeoylfa\n" +
            "pphcuxsvrnjzxwkbgdtmeoylfa\n" +
            "mphiuvsvrnjzxlkbgdtqeoylfa\n" +
            "mphlqisvrnjzxkkbgdtqeoylfa\n" +
            "mmhcuisvrnjzxwkbgatqeoylea\n" +
            "mphduisrrnjoxwkbgdtqeoylfa\n" +
            "mphcuisvrnjnxwkvgdyqeoylfa\n" +
            "mphcuvsvrnjzxgkbgdtqeoylfz\n" +
            "mphcuisvryjzxwkbggtqkoylfa\n" +
            "iphcuisvrdjzxwkbgotqeoylfa\n" +
            "mphcuisvrnjzxwhbgdtqwoyofa\n" +
            "mphcorbvrnjzxwkbgdtqeoylfa\n" +
            "mghcuisvrnpzxykbgdtqeoylfa\n" +
            "mphauisvrnjnxwkbzdtqeoylfa\n" +
            "mphcgisvrnjzxwkwgdtqeoygfa\n" +
            "mphcuisvrnjzxwkggotqeoylba\n" +
            "mphcuesvrnjzxwkbgdwqebylfa\n" +
            "yphcuisvrnjzxwkbgdxqeoylja\n" +
            "ephyuisvrnjzywkbgdtqeoylfa\n" +
            "mfhcuisqrnjzxwkbgdlqeoylfa\n" +
            "mphkuisvrnjzxwkbertqeoylfa\n" +
            "mphcuusgrnjzxwkbggtqeoylfa\n" +
            "mphcuildrnjvxwkbgdtqeoylfa\n" +
            "mphcuiuvrnjzlwkbgwtqeoylfa\n" +
            "mppcuisvrljzxwkbgdtqeoylfw\n" +
            "mphcwiwvrnjzxwsbgdtqeoylfa\n" +
            "mphcubivrnjzxwkqgdtqeoylfa\n" +
            "mphcuisvrnjpxwkngdtqeoylpa\n" +
            "pchcuisvrgjzxwkbgdtqeoylfa\n" +
            "mphcuisvlnjzxwkbgdtmeoylfw\n" +
            "mphcuisvrnjzywkbgdvqeoylfj\n" +
            "mpzcuisvrnezxwktgdtqeoylfa\n" +
            "mphcuisvrnjbxwkbgzrqeoylfa\n" +
            "mphcuisvrnjzxwktgdtqeodtfa\n" +
            "jphcuiavrnjzxwkbgdtqeoylfv\n" +
            "mphcuisvrnjzxwkbddppeoylfa\n" +
            "mphcuissrkjzxwkbgxtqeoylfa\n" +
            "mphcuisvrhjzxwxbgdtqeoylxa\n" +
            "mphcvisvgnjjxwkbgdtqeoylfa\n" +
            "mphcuisprnjwxwtbgdtqeoylfa\n" +
            "mphcuissrnjzxqkbgdtqeoymfa\n" +
            "mphcuiabrnjzxokbgdtqeoylfa\n" +
            "mphcuisvrnczxwkbgmtpeoylfa";
}